/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftCollectionSol from "./NFTCollection.sol";
export type { nftCollectionSol };
export type { SLEPToken } from "./SLEPToken";
export type { StakingToken } from "./StakingToken";
